window.isMobile=!1;if(/Android|webOS|iPhone|iPad|iPod|BlackBerry|IEMobile|Opera Mini/i.test(navigator.userAgent)){window.isMobile=!0}
window.isSafari=!1;if(/^((?!chrome|android).)*safari/i.test(navigator.userAgent)){window.isSafari=!0}
window.isSafariVersion='';if(window.isSafari){var version=(navigator.appVersion).match(/Version\/(\d+)\.(\d+)\.?(\d+)? Safari/);if(version!==null){window.isSafariVersion=[parseInt(version[1],10),parseInt(version[2],10),parseInt(version[3]||0,10)]}}
function t_throttle(fn,threshhold,scope){var last;var deferTimer;threshhold||(threshhold=250);return function(){var context=scope||this;var now=+new Date();var args=arguments;if(last&&now<last+threshhold){clearTimeout(deferTimer);deferTimer=setTimeout(function(){last=now;fn.apply(context,args)},threshhold)}else{last=now;fn.apply(context,args)}}}
function t670_init(recid,isEditMode){var rec=document.getElementById('rec'+recid);if(!rec)return;var image=rec.querySelector('.t-img');if(image){if(image.complete){t670_addImageEvents(recid,isEditMode)}else{image.addEventListener('load',function(){t670_addImageEvents(recid,isEditMode)});image.addEventListener('error',function(){t670_addImageEvents(recid,isEditMode)})}}else{t670_addImageEvents(recid,isEditMode)}}
const t670_postMessages={youtube:{pause:'{"event":"command","func":"pauseVideo","args":""}',play:'{"event":"command","func":"playVideo","args":""}',},rutube:{pause:'{"type":"player:pause","data":"{}"}',play:'{"type":"player:play","data":"{}"}',},vimeo:{pause:'{"method":"pause","value":"true"}',play:'{"method":"play","value":"true"}',},};function t670_addImageEvents(recid,isEditMode){var rec=document.getElementById('rec'+recid);t670_imageHeight(rec);t670_show(rec);t670_hide(rec);t670_addArrowHandlers(rec);t_onFuncLoad('t_sldsInit',function(){t_sldsInit(recid)});if(isEditMode){t_onFuncLoad('t_slds_UpdateSliderHeight',function(){t_slds_UpdateSliderHeight(recid)});t_onFuncLoad('t_slds_UpdateSliderArrowsHeight',function(){t_slds_UpdateSliderArrowsHeight(recid)})}
var wrapper=rec.querySelector('.t670');if(wrapper){wrapper.addEventListener('displayChanged',function(){t_onFuncLoad('t_slds_updateSlider',function(){t_slds_updateSlider(recid)});t_onFuncLoad('t_slds_positionArrows',function(){t_slds_positionArrows(recid)})})}}
function t670_handleRutube(videoWrap,videoLazy){var videoId=videoLazy.getAttribute('data-videolazy-id');if(videoId)videoId=videoId.replace(/[^\w-]/g,'');if(!videoId)return;var videoHash=videoLazy.getAttribute('data-videolazy-hash');if(videoHash)videoHash=videoHash.replace(/[^\w-]/g,'');var existingIframe=videoWrap.querySelector('iframe.t670__rutube-iframe');if(!existingIframe){var src='https://rutube.ru/play/embed/'+videoId+'/?autoplay=1&muted=1&playsinline=1';if(videoHash)src+='&p='+videoHash;videoWrap.innerHTML='';var iframe=document.createElement('iframe');iframe.className='t670__rutube-iframe';iframe.setAttribute('allow','autoplay; fullscreen');iframe.setAttribute('allowfullscreen','');iframe.setAttribute('frameborder','0');iframe.style.width='100%';iframe.style.height='100%';iframe.style.display='block';iframe.src=src;videoWrap.appendChild(iframe)}else{try{existingIframe.contentWindow.postMessage(t670_postMessages.rutube.play,'*')}catch(e){console.warn('Failed to send play message to Rutube iframe:',e)}}}
function t670_show(rec){var playBtns=rec.querySelectorAll('.t670__play');Array.prototype.forEach.call(playBtns,function(play){var itemWrap=play.closest('.t670__imgwrapper');var image=itemWrap.querySelector('.t-slds__bgimg');var videoWrap=itemWrap.querySelector('.t670__wrap-video');var videoLazy=videoWrap.querySelector('.t-video-lazyload');play.addEventListener('click',function(event){event.preventDefault();videoWrap.style.display='block';image.style.opacity=0;var type=videoLazy.getAttribute('data-videolazy-type');if(type==='rutube'){t670_handleRutube(videoWrap,videoLazy)}else{t_onFuncLoad('t_video_lazyload__addVideo',function(){t_video_lazyload__addVideo(videoLazy)})}})})}
function t670_pauseVideo(videoWrap){if(!videoWrap)return;var iframe=videoWrap.querySelector('iframe');if(iframe&&iframe.contentWindow&&iframe.src){var videoSRC=iframe.src;if(videoSRC.indexOf('&enablejsapi=1')!==-1){iframe.contentWindow.postMessage(t670_postMessages.youtube.pause,'*')}
if(videoSRC.indexOf('rutube')!==-1){iframe.contentWindow.postMessage(t670_postMessages.rutube.pause,'*')}
if(videoSRC.indexOf('vimeo')!==-1&&videoSRC.indexOf('&api=1')!==-1){iframe.contentWindow.postMessage(t670_postMessages.vimeo.pause,'*')}}
var videoEl=videoWrap.querySelector('video');if(videoEl&&typeof videoEl.pause==='function'){try{videoEl.pause()}catch(e){console.warn('t670: Failed to pause video element:',e)}}}
function t670_hide(rec){var videoWraps=rec.querySelectorAll('.t670__wrap-video');rec.addEventListener('updateSlider',function(){Array.prototype.forEach.call(videoWraps,function(videoWrap){t670_pauseVideo(videoWrap);var hasIframe=videoWrap.querySelector('iframe');if(!hasIframe){videoWrap.style.display='none'}})})}
function t670_addArrowHandlers(rec){if(!rec)return;if(rec.t670ArrowsInitialized){return}
rec.t670ArrowsInitialized='true';rec.addEventListener('click',function(event){var arrow=event.target.closest('.t-slds__arrow_wrapper');if(!arrow)return;t670_pauseAllVideos(rec)})}
function t670_pauseAllVideos(rec){if(!rec)return;var videoWraps=rec.querySelectorAll('.t670__wrap-video');Array.prototype.forEach.call(videoWraps,function(videoWrap){t670_pauseVideo(videoWrap);var hasIframe=videoWrap.querySelector('iframe');if(!hasIframe){videoWrap.style.display='none';var imgWrapper=videoWrap.closest('.t670__imgwrapper');if(imgWrapper){var bgImg=imgWrapper.querySelector('.t-slds__bgimg');if(bgImg){bgImg.style.opacity=1}}}})}
function t670_imageHeight(rec){var images=rec.querySelectorAll('.t670__separator');Array.prototype.forEach.call(images,function(img){var width=parseInt(img.getAttribute('data-slider-image-width'))||0;var height=parseInt(img.getAttribute('data-slider-image-height'))||0;var ratio=height/width;var padding=ratio*100;img.style.paddingBottom=padding+'%'})}
function t678_onSuccess(form){t_onFuncLoad('t_forms__onSuccess',function(){t_forms__onSuccess(form)})}
function t690_onSuccess(form){t_onFuncLoad('t_forms__onSuccess',function(){t_forms__onSuccess(form)})}
function t674_init(recid){var rec=document.getElementById('rec'+recid);if(!rec)return;var backgroundImage=rec.querySelector('.t674__img-holder');if(!backgroundImage)return;backgroundImage.onload=function(){var delay=0;var allRecords=document.getElementById('allrecords');if(allRecords.getAttribute('data-blocks-animationoff')!=='yes'){delay=600}
setTimeout(function(){document.body.classList.add('t674__body_with-bg')},delay)};var event=document.createEvent('HTMLEvents');event.initEvent('load',!0,!1);backgroundImage.dispatchEvent(event)}
window.requestAnimationFrame=(function(){return(window.requestAnimationFrame||window.webkitRequestAnimationFrame||window.mozRequestAnimationFrame||window.oRequestAnimationFrame||window.msRequestAnimationFrame||function(callback){window.setTimeout(callback,1000/60)})})();function t270_scroll(hash,offset){if(!hash)return;t270_checkLoad(hash,offset);var excludeHashes=['#!/tproduct/','#!/tab/','#opencart'];if(excludeHashes.includes(hash)){return!0}
var isHistoryChangeAllowed=window.location.hash!==hash;var wrapperBlock=document.querySelector('.t270');var dontChangeHistory=wrapperBlock?Boolean(wrapperBlock.getAttribute('data-history-disabled')):!1;t270_scrollToEl(hash,offset);if(!dontChangeHistory&&isHistoryChangeAllowed){if(history.pushState){history.pushState(null,null,hash)}else{window.location.hash=hash}
isHistoryChangeAllowed=!1}
return!0}
function t270_checkLoad(hash,offset){if(window.t270_loadChecked)return;var sliderWrappers=document.body.querySelectorAll('.t-slds__items-wrapper');if(!sliderWrappers.length)return;var lastWrapper=sliderWrappers[sliderWrappers.length-1];var sliderImgs=lastWrapper?lastWrapper.querySelectorAll('.t-slds__bgimg'):[];var lastImg=sliderImgs[sliderImgs.length-1];var imageUrl=lastImg?window.getComputedStyle(lastImg).backgroundImage:'';imageUrl=imageUrl.substring(5,imageUrl.length-2);var preloaderImg=document.createElement('img');preloaderImg.src=imageUrl?imageUrl:'';preloaderImg.addEventListener('load',function(){t270_scroll(hash,offset);window.t270_loadChecked=!0})}
function t270_scrollToEl(hash,offset){var SCROLL_DURATION_MS=500;var body=document.body;if(body.getAttribute('data-scroll'))return;var scrollTargetY=t270_getTarget(hash,offset);if(isNaN(scrollTargetY))return;var canSmoothScroll=window.CSS&&window.CSS.supports('scroll-behavior','smooth')&&'scrollBehavior' in document.documentElement.style;var userAgent=navigator.userAgent.toLowerCase();var isAndroid=userAgent.indexOf('android')!==-1;if(window.isMobile&&!isAndroid&&canSmoothScroll){body.setAttribute('data-scroll','true');window.scrollTo({left:0,top:scrollTargetY,behavior:'smooth',});setTimeout(function(){body.removeAttribute('data-scroll')},SCROLL_DURATION_MS)}else{t270_smoothScrollTo(scrollTargetY,SCROLL_DURATION_MS)}}
function t270_smoothScrollTo(targetY,duration=500){var body=document.body;var startY=window.scrollY||window.pageYOffset;var deltaY=targetY-startY;var startTime=performance.now();function easeInOutQuad(t){return Math.pow(t,2)}
function scroll(){var currentTime=performance.now();var elapsedTime=Math.min((currentTime-startTime)/duration,1);var ease=easeInOutQuad(elapsedTime);window.scrollTo(0,startY+deltaY*ease);if(elapsedTime<1){requestAnimationFrame(scroll)}else{body.removeAttribute('data-scroll');body.removeAttribute('data-scrollable');window.scrollTo(0,targetY)}}
body.setAttribute('data-scroll','true');body.setAttribute('data-scrollable','true');requestAnimationFrame(scroll)}
function t270_getTarget(hash,offset){var target;try{if(hash.substring(0,1)==='#'){target=document.getElementById(hash.substring(1))}else{target=document.querySelector(hash)}}catch(event){console.log('Exception t270: '+event.message);return}
if(!target){target=document.querySelector('a[name="'+hash.substr(1)+'"], div[id="'+hash.substr(1)+'"]');if(!target)return}
target=parseInt(target.getBoundingClientRect().top+window.pageYOffset-offset,10);target=Math.max(target,0);return target}
function t824_init(recId){var rec=document.getElementById('rec'+recId);if(!rec)return;var container=rec.querySelector('.t824');if(!container)return;rec.setAttribute('data-animationappear','off');rec.style.opacity=1;var popup=rec.querySelector('.t824__popup');var analitics=popup.getAttribute('data-track-popup');var hook='TildaSendMessageWidget'+recId;var button=rec.querySelector('.t824__btn');var closeButtons=rec.querySelectorAll('.t824__popup-close, .t824__mobile-close');var popupContainer=rec.querySelector('.t824__popup-container');window.addEventListener('scroll',t_throttle(function(){t824_appearPopup(recId)},200));button.addEventListener('click',function(event){container.classList.add('t824_active');t824_showPopup(recId);popupContainer.style.visibility='visible';t824__fadeIn(popupContainer);button.style.visibility='hidden';t824__fadeOut(button);if(analitics&&window.Tilda){Tilda.sendEventToStatistics(analitics,hook)}
event.preventDefault()});for(var i=0;i<closeButtons.length;i++){closeButtons[i].addEventListener('click',function(event){t824_closePopup(rec);event.preventDefault()})}
document.addEventListener('keydown',function(event){t824_escClosePopup(event,rec)});t824_appearPopup(recId);t824_checkPhoneNumber(rec)}
function t824_showPopup(recId){var rec=document.getElementById('rec'+recId);if(!rec)return;var container=rec.querySelector('.t824');if(!container)return;var popup=rec.querySelector('.t824__popup');var buttonWrapper=rec.querySelector('.t824__btn_wrapper');var buttonText=rec.querySelector('.t824__btn-text');if(buttonWrapper)buttonWrapper.classList.remove('t824__btn_animate');if(buttonText)buttonText.style.display='none';if(window.innerWidth<960)document.body.classList.add('t824__body_popupshowed');popup.style.display='block';setTimeout(function(){popup.classList.add('t824__popup_show')},50);t824__lazyLoad()}
function t824_escClosePopup(event,rec){if(event.key==='Escape')t824_closePopup(rec)}
function t824_closePopup(rec){if(window.innerWidth<960)document.body.classList.remove('t824__body_popupshowed');var container=rec.querySelector('.t824');var popup=rec.querySelector('.t824__popup');var button=rec.querySelector('.t824__btn');var popupContainer=rec.querySelector('.t824__popup-container');var appearOffset=popupContainer.getAttribute('data-appearoffset');container.classList.remove('t824_active');popup.classList.remove('t824__popup_show');setTimeout(function(){var popupHide=rec.querySelector('.t824__popup:not(.t824__popup_show)');popupHide.style.display='none'},300);if(appearOffset){if(appearOffset.indexOf('vh')>-1){appearOffset=Math.floor(window.innerHeight*(parseInt(appearOffset)/100))}
appearOffset=parseInt(appearOffset,10);if(window.pageYOffset>=appearOffset){button.style.visibility='visible';t824__fadeIn(button);t824__lazyLoad()}}else{button.style.visibility='visible';t824__fadeIn(button);t824__lazyLoad()}}
function t824_checkPhoneNumber(rec){var phone=rec.querySelector('.t824__phone');if(!phone)return;var phoneText=phone.textContent;if(phoneText){phone.href='tel:'+phoneText.replace(/[^0-9,+]/g,'')}}
function t824_sendPopupEventToStatistics(popupName){var virtPage='/tilda/popup/';var virtTitle='Popup: ';if(popupName.substring(0,7)=='#popup:'){popupName=popupName.substring(7)}
virtPage+=popupName;virtTitle+=popupName;if(window.Tilda&&typeof Tilda.sendEventToStatistics=='function'){Tilda.sendEventToStatistics(virtPage,virtTitle,'',0)}else{if(ga){if(window.mainTracker!='tilda'){ga('send',{hitType:'pageview',page:virtPage,title:virtTitle})}}
if(window.mainMetrika&&window[window.mainMetrika]){window[window.mainMetrika].hit(virtPage,{title:virtTitle,referer:window.location.href})}}}
function t824_appearPopup(recId){if(window.innerWidth>980){var rec=document.getElementById('rec'+recId);var container=rec.querySelector('.t824');var popup=rec.querySelector('.t824__popup');var popupContainer=rec.querySelector('.t824__popup-container');var button=rec.querySelector('.t824__btn');var appearOffset=popupContainer.getAttribute('data-appearoffset');var popupContainerStyle=getComputedStyle(popupContainer,null).visibility;var buttonStyle=getComputedStyle(button,null);if(appearOffset){if(appearOffset.indexOf('vh')>-1){appearOffset=Math.floor(window.innerHeight*(parseInt(appearOffset)/100))}
appearOffset=parseInt(appearOffset,10);if(window.pageYOffset>=appearOffset){if(!container.classList.contains('t824_active')&&buttonStyle.visibility==='hidden'){button.style.visibility='visible';t824__fadeIn(button)}}else{if(popupContainerStyle==='hidden'&&buttonStyle.visibility==='hidden'&&buttonStyle.display!=='none'){popup.style.display='block';setTimeout(function(){popup.classList.add('t824__popup_show')},50);container.classList.add('t824_active');popupContainer.style.visibility='visible';t824__lazyLoad();t824__fadeIn(popupContainer)}else if(!container.classList.contains('t824_active')&&buttonStyle.visibility!=='hidden'){button.style.visibility='hidden';t824__fadeOut(button)}}}else{if(popupContainerStyle==='hidden'&&buttonStyle.visibility==='hidden'){popup.style.display='block';setTimeout(function(){popup.classList.add('t824__popup_show')},50);container.classList.add('t824_active');popupContainer.style.visibility='visible';t824__lazyLoad();t824__fadeIn(popupContainer)}}}}
function t824__lazyLoad(){if(window.lazy==='y'||document.getElementById('allrecords').getAttribute('data-tilda-lazy')==='yes'){t_onFuncLoad('t_lazyload_update',function(){t_lazyload_update()})}}
function t824__fadeOut(el){if(el.style.display==='none')return;var opacity=1;var timer=setInterval(function(){el.style.opacity=opacity;opacity-=0.1;if(opacity<=0.1){clearInterval(timer);el.style.display='none';el.style.opacity=''}},20)}
function t824__fadeIn(el){if(el.style.display==='block')return;var opacity=0;el.style.opacity=opacity;el.style.display='block';var timer=setInterval(function(){el.style.opacity=opacity;opacity+=0.1;if(opacity>=1.0){clearInterval(timer);el.style.display=''}},20)}
function t390_initPopup(recId){var rec=document.getElementById('rec'+recId);if(!rec)return;var container=rec.querySelector('.t390');if(!container)return;rec.setAttribute('data-animationappear','off');rec.style.opacity=1;var popup=rec.querySelector('.t-popup');var popupTooltipHook=popup.getAttribute('data-tooltip-hook');var analitics=popup.getAttribute('data-track-popup');var popupCloseBtn=popup.querySelector('.t-popup__close');var hrefs=rec.querySelectorAll('a[href*="#"]');var escapeEvent=t390_escClosePopup.bind(this,recId);if(popupTooltipHook){t_onFuncLoad('t_popup__addAttributesForAccessibility',function(){t_popup__addAttributesForAccessibility(popupTooltipHook)});document.addEventListener('click',function(event){var target=event.target;var href=target.closest('a[href="'+popupTooltipHook+'"]')?target:!1;if(!href)return;event.preventDefault();t390_showPopup(recId,escapeEvent);t_onFuncLoad('t_popup__resizePopup',function(){t_popup__resizePopup(recId)});t390__lazyLoad();if(analitics&&window.Tilda){Tilda.sendEventToStatistics(analitics,popupTooltipHook)}});t_onFuncLoad('t_popup__addClassOnTriggerButton',function(){t_popup__addClassOnTriggerButton(document,popupTooltipHook)})}
popup.addEventListener('scroll',t_throttle(function(){t390__lazyLoad()}));popup.addEventListener('click',function(event){if(event.target===this)t390_closePopup(recId,escapeEvent)});popupCloseBtn.addEventListener('click',function(){t390_closePopup(recId,escapeEvent)});for(var i=0;i<hrefs.length;i++){hrefs[i].addEventListener('click',function(){var url=this.getAttribute('href');if(!url||url.substring(0,7)!='#price:'){t390_closePopup(recId,escapeEvent);if(!url||url.substring(0,7)=='#popup:'){setTimeout(function(){if(typeof t_triggerEvent==='function')t_triggerEvent(document.body,'popupShowed');document.body.classList.add('t-body_popupshowed')},300)}}})}
var curPath=window.location.pathname;var curFullPath=window.location.origin+curPath;var isAndroid=/(android)/i.test(navigator.userAgent);if(isAndroid){var selects='a[href^="#"]:not([href="#"]):not([href^="#price"]):not([href^="#popup"]):not([href^="#prodpopup"]):not([href^="#order"]):not([href^="#!"]),'+'a[href^="'+curPath+'#"]:not([href*="#!/tproduct/"]):not([href*="#!/tab/"]):not([href*="#popup"]),'+'a[href^="'+curFullPath+'#"]:not([href*="#!/tproduct/"]):not([href*="#!/tab/"]):not([href*="#popup"])';var selectors=rec.querySelectorAll(selects);for(var i=0;i<selectors.length;i++){selectors[i].addEventListener('click',function(event){var hash=this.hash.trim();if(window.location.hash){setTimeout(function(){window.location.href=hash},50)}})}}
function t390_escClosePopup(recId){if(arguments[1].key==='Escape')t390_closePopup(recId,escapeEvent)}}
function t390_showPopup(recId,escapeEvent){var rec=document.getElementById('rec'+recId);if(!rec)return;var container=rec.querySelector('.t390');if(!container)return;var windowWidth=window.innerWidth;var screenMin=rec.getAttribute('data-screen-min');var screenMax=rec.getAttribute('data-screen-max');if(screenMin&&windowWidth<parseInt(screenMin,10))return;if(screenMax&&windowWidth>parseInt(screenMax,10))return;var popup=rec.querySelector('.t-popup');var documentBody=document.body;t_onFuncLoad('t_popup__showPopup',function(){t_popup__showPopup(popup)});if(typeof t_triggerEvent==='function')t_triggerEvent(document.body,'popupShowed');documentBody.classList.add('t-body_popupshowed');documentBody.classList.add('t390__body_popupshowed');document.addEventListener('keydown',escapeEvent)}
function t390_closePopup(recId,escapeEvent){var rec=document.getElementById('rec'+recId);var popup=rec.querySelector('.t-popup');var popupActive=document.querySelector('.t-popup.t-popup_show');if(popup===popupActive){if(typeof t_triggerEvent==='function')t_triggerEvent(document.body,'popupHidden');document.body.classList.remove('t-body_popupshowed');document.body.classList.remove('t390__body_popupshowed')}
popup.classList.remove('t-popup_show');t_onFuncLoad('t_popup__addFocusOnTriggerButton',function(){t_popup__addFocusOnTriggerButton()});setTimeout(function(){var popupHide=document.querySelectorAll('.t-popup:not(.t-popup_show)');for(var i=0;i<popupHide.length;i++){popupHide[i].style.display='none'}},300);document.removeEventListener('keydown',escapeEvent)}
function t390_sendPopupEventToStatistics(popupName){var virtPage='/tilda/popup/';var virtTitle='Popup: ';if(popupName.substring(0,7)=='#popup:'){popupName=popupName.substring(7)}
virtPage+=popupName;virtTitle+=popupName;if(window.Tilda&&typeof Tilda.sendEventToStatistics=='function'){Tilda.sendEventToStatistics(virtPage,virtTitle,'',0)}else{if(ga){if(window.mainTracker!='tilda'){ga('send',{hitType:'pageview',page:virtPage,title:virtTitle})}}
if(window.mainMetrika&&window[window.mainMetrika]){window[window.mainMetrika].hit(virtPage,{title:virtTitle,referer:window.location.href})}}}
function t390__lazyLoad(){var allRecords=document.getElementById('allrecords');if(window.lazy==='y'||(allRecords&&allRecords.getAttribute('data-tilda-lazy')==='yes')){t_onFuncLoad('t_lazyload_update',function(){t_lazyload_update()})}}
function t367_createCookie(cookieName,cookieValue,cookieTime){var expires='';if(cookieTime){if(Number(cookieTime)>9999999){cookieTime=9999999}
var date=new Date();date.setTime(date.getTime()+cookieTime*24*60*60*1000);expires='; expires='+date.toGMTString()}
document.cookie=cookieName+'='+cookieValue+expires+'; path=/'}
function t367_readCookie(cookieName){cookieName=cookieName+'=';var allCookies=document.cookie.split(';');for(var i=0;i<allCookies.length;i++){var cookie=allCookies[i];while(cookie.charAt(0)===' '){cookie=cookie.substring(1,cookie.length)}
if(cookie.indexOf(cookieName)===0){return cookie.substring(cookieName.length,cookie.length)}}
return null}
function checkIsValidLink(link){try{const url=new URL(link,window.location.href);return['http:','https:'].includes(url.protocol)}catch{return!1}}
function t367_autoInit(recid){var rec=document.querySelector('#rec'+recid);if(!rec)return;var screenMin=rec.getAttribute('data-screen-min');var screenMax=rec.getAttribute('data-screen-max');var windowWidth=window.innerWidth;if(typeof screenMin==='string'){if(windowWidth<parseInt(screenMin,10)){return!0}}
if(typeof screenMax==='string'){if(windowWidth>parseInt(screenMax,10)){return!0}}
var openerLink=rec.querySelector('.t367__opener');if(!t367_isPopupRecVisible(openerLink))return;var linkhook=openerLink.getAttribute('href');if(!linkhook)return;var cookieName=openerLink.getAttribute('data-cookie-name');var cookieTime=openerLink.getAttribute('data-cookie-time');var cookieValue='t367cookie';var cookie=t367_readCookie(cookieName);var timeout=parseInt(openerLink.getAttribute('data-trigger-time'),10)*1000;var wrapperBlock=rec.querySelector('.t367');if(!wrapperBlock)return;if(cookie){wrapperBlock.innerHTML=''}else if(openerLink&&checkIsValidLink(openerLink)){setTimeout(function(){openerLink.click();wrapperBlock.innerHTML='';t367_createCookie(cookieName,cookieValue,cookieTime)},timeout)}}
function t367_isPopupRecVisible(openerLink){if(openerLink){var linkText=openerLink.getAttribute('href');var popupElement=document.querySelector('.t-popup[data-tooltip-hook="'+linkText+'"]');if(popupElement){var popupElementRec=popupElement.closest('.r');var minScreen=popupElementRec.getAttribute('data-screen-min');if(minScreen&&minScreen!==''){minScreen=minScreen.replace('px','');if(parseInt(minScreen,10)>window.innerWidth){return!1}}
var maxScreen=popupElementRec.getAttribute('data-screen-max');if(maxScreen&&maxScreen!==''){maxScreen=maxScreen.replace('px','');if(parseInt(maxScreen,10)<window.innerWidth){return!1}}}
return!0}}
function t875_init(){if(document.layers){document.captureEvents(Event.MOUSEDOWN)}
document.onmousedown=t875_click;document.oncontextmenu=function(event){event=event||window.event;var sender=event.target||event.srcElement;if(sender&&(sender.tagName.match(/INPUT|TEXTAREA/i)||sender.hasAttribute('contenteditable')||(sender.parentElement&&sender.parentElement.hasAttribute('contenteditable')))){return}else{return!1}};t875_preventSelection(document);t875_preventUserSelect()}
function t875_preventUserSelect(){var oldStyle=document.body.getAttribute('style');document.body.style.cssText=oldStyle+'-ms-user-select: none;'+'-moz-user-select: none;'+'-webkit-user-select: none;'+'user-select: none;'+'-webkit-touch-callout: none;'}
function t875_click(event){t875_returnPrevent(event);if(document.all){if(event.button===2){return!1}}
if(document.layers){if(event.which===3){return!1}}}
function t875_preventSelection(element){var preventSelection=!1;t875_addHandler(element,'mousemove',function(){if(preventSelection){t875_removeSelection()}});t875_addHandler(element,'mousedown',function(event){event=event||window.event;var sender=event.target||event.srcElement;preventSelection=sender&&!sender.tagName.match(/INPUT|TEXTAREA/i)&&!sender.hasAttribute('contenteditable')&&sender.parentElement&&!sender.parentElement.hasAttribute('contenteditable')});t875_addHandler(element,'mouseup',function(){if(preventSelection){t875_removeSelection()}
preventSelection=!1});t875_addHandler(element,'keydown',t875_killCtrlA);t875_addHandler(element,'keyup',t875_killCtrlA);t875_addHandler(element,'keydown',t875_killCtrlU);t875_addHandler(element,'keyup',t875_killCtrlU);t875_addHandler(element,'keydown',t875_killAltCmdI);t875_addHandler(element,'keyup',t875_killAltCmdI);t875_addHandler(element,'keydown',t875_killCtrlShiftI);t875_addHandler(element,'keyup',t875_killCtrlShiftI)}
function t875_addHandler(element,event,handler){if(element.attachEvent){element.attachEvent('on'+event,handler)}else if(element.addEventListener){element.addEventListener(event,handler,!1)}}
function t875_removeSelection(){if(window.getSelection){window.getSelection().removeAllRanges()}else if(document.selection&&document.selection.clear){document.selection.clear()}}
function t875_killCtrlU(event){t875_returnPrevent(event);var key=event.keyCode||event.which;if((event.ctrlKey&&key=='U'.charCodeAt(0))||(event.altKey&&event.metaKey&&(key=='U'.charCodeAt(0)||key=='u'.charCodeAt(0)))){if(event.preventDefault){event.preventDefault()}else{event.returnValue=!1}}}
function t875_killAltCmdI(event){t875_returnPrevent(event);var key=event.keyCode||event.which;if(event.altKey&&event.metaKey&&(key=='I'.charCodeAt(0)||key=='i'.charCodeAt(0))){if(event.preventDefault){event.preventDefault()}else{event.returnValue=!1}}}
function t875_killCtrlShiftI(event){t875_returnPrevent(event);var key=event.keyCode||event.which;if(event.shiftKey&&event.ctrlKey&&(key=='I'.charCodeAt(0)||key=='i'.charCodeAt(0))){if(event.preventDefault){event.preventDefault()}else{event.returnValue=!1}}}
function t875_killCtrlA(event){event=event||window.event;var sender=event.target||event.srcElement;if(sender&&(sender.tagName.match(/INPUT|TEXTAREA|BUTTON/i)||sender.hasAttribute('contenteditable')||(sender.parentElement&&sender.parentElement.hasAttribute('contenteditable')))){return}
var key=event.keyCode||event.which;if((event.ctrlKey&&key=='A'.charCodeAt(0))||(event.metaKey&&key=='A'.charCodeAt(0))){t875_removeSelection();if(event.preventDefault){event.preventDefault()}else{event.returnValue=!1}}}
function t875_returnPrevent(event){event=event||window.event;var sender=event.target||event.srcElement;if(sender&&(sender.tagName.match(/INPUT|TEXTAREA/i)||sender.hasAttribute('contenteditable')||(sender.parentElement&&sender.parentElement.hasAttribute('contenteditable')))){return}}